services:
  app:
    build: .
    stdin_open: true
    tty: true
    user: user
    volumes:
      - ./ExampleProject:/home/user/ExampleProject
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=$DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
